/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formatki;

import bazaslowek.BazaDanych;

/**
 *
 * @author joann
 */
public class CharakterFrame extends javax.swing.JFrame {

    /**
     * Creates new form LekarzFrame
     */
    public CharakterFrame() {
        initComponents();
        setTitle("Kategorie / Cechy charakteru");
        bd = new BazaDanych();
//        lf = new LekarzFrame();
//        zf = new ZwrotyFrame();
//        uf = new UbraniaFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bWylosuj = new rojerusan.RSButtonPane();
        jLabel1 = new javax.swing.JLabel();
        bSprawdz = new rojerusan.RSButtonPane();
        jLabel2 = new javax.swing.JLabel();
        tTlumacz = new javax.swing.JTextField();
        tSlowko = new javax.swing.JTextArea();
        bCharakter = new rojerusan.RSButtonIconD();
        bUbrania = new rojerusan.RSButtonIconD();
        bZwroty = new rojerusan.RSButtonIconD();
        bLekarz = new rojerusan.RSButtonIconD();

        jPanel1.setBackground(new java.awt.Color(46, 68, 133));

        bWylosuj.setBackground(new java.awt.Color(46, 68, 133));
        bWylosuj.setColorHover(new java.awt.Color(33, 50, 103));
        bWylosuj.setColorNormal(new java.awt.Color(46, 68, 133));
        bWylosuj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bWylosujMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(213, 187, 155));
        jLabel1.setText("WYLOSUJ");

        javax.swing.GroupLayout bWylosujLayout = new javax.swing.GroupLayout(bWylosuj);
        bWylosuj.setLayout(bWylosujLayout);
        bWylosujLayout.setHorizontalGroup(
            bWylosujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bWylosujLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        bWylosujLayout.setVerticalGroup(
            bWylosujLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bWylosujLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bSprawdz.setBackground(new java.awt.Color(46, 68, 133));
        bSprawdz.setColorHover(new java.awt.Color(33, 50, 103));
        bSprawdz.setColorNormal(new java.awt.Color(46, 68, 133));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(213, 187, 155));
        jLabel2.setText("SPRAWDŹ");

        javax.swing.GroupLayout bSprawdzLayout = new javax.swing.GroupLayout(bSprawdz);
        bSprawdz.setLayout(bSprawdzLayout);
        bSprawdzLayout.setHorizontalGroup(
            bSprawdzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bSprawdzLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(51, 51, 51))
        );
        bSprawdzLayout.setVerticalGroup(
            bSprawdzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bSprawdzLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tTlumacz.setBackground(new java.awt.Color(46, 68, 133));
        tTlumacz.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        tTlumacz.setForeground(new java.awt.Color(213, 187, 155));
        tTlumacz.setText("Przetłumacz na polski...");
        tTlumacz.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(213, 187, 155)));
        tTlumacz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tTlumaczMouseClicked(evt);
            }
        });
        tTlumacz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTlumaczActionPerformed(evt);
            }
        });

        tSlowko.setBackground(new java.awt.Color(46, 68, 133));
        tSlowko.setColumns(20);
        tSlowko.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        tSlowko.setForeground(new java.awt.Color(213, 187, 155));
        tSlowko.setLineWrap(true);
        tSlowko.setRows(5);
        tSlowko.setWrapStyleWord(true);
        tSlowko.setCaretColor(new java.awt.Color(213, 187, 155));
        tSlowko.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tSlowko.setDisabledTextColor(new java.awt.Color(213, 187, 155));
        tSlowko.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tSlowko.setSelectedTextColor(new java.awt.Color(213, 187, 155));

        bCharakter.setBackground(new java.awt.Color(46, 68, 133));
        bCharakter.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(213, 187, 155)));
        bCharakter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formatki/ikonki/charakter.png"))); // NOI18N
        bCharakter.setColorHover(new java.awt.Color(33, 50, 103));
        bCharakter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCharakterActionPerformed(evt);
            }
        });

        bUbrania.setBackground(new java.awt.Color(46, 68, 133));
        bUbrania.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formatki/ikonki/ubrania.png"))); // NOI18N
        bUbrania.setColorHover(new java.awt.Color(33, 50, 103));
        bUbrania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbraniaActionPerformed(evt);
            }
        });

        bZwroty.setBackground(new java.awt.Color(46, 68, 133));
        bZwroty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formatki/ikonki/zwroty.png"))); // NOI18N
        bZwroty.setColorHover(new java.awt.Color(33, 50, 103));
        bZwroty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bZwrotyActionPerformed(evt);
            }
        });

        bLekarz.setBackground(new java.awt.Color(46, 68, 133));
        bLekarz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formatki/ikonki/lekarz.png"))); // NOI18N
        bLekarz.setColorHover(new java.awt.Color(33, 50, 103));
        bLekarz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLekarzActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bWylosuj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(bSprawdz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bLekarz, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bCharakter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bUbrania, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bZwroty, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tSlowko, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(tTlumacz, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bCharakter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUbrania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bZwroty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLekarz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tSlowko, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tTlumacz, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSprawdz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bWylosuj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tSlowko.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tTlumaczActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTlumaczActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTlumaczActionPerformed

    private void tTlumaczMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTlumaczMouseClicked
        // TODO add your handling code here:
        tTlumacz.setText("");
    }//GEN-LAST:event_tTlumaczMouseClicked

    private void bWylosujMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bWylosujMouseClicked
        // TODO add your handling code here:
        tSlowko.setText("");
        bd.losCharakter(tSlowko, tTlumacz);
       
        
    }//GEN-LAST:event_bWylosujMouseClicked

    private void bCharakterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCharakterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCharakterActionPerformed

    private void bUbraniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbraniaActionPerformed
        // TODO add your handling code here:
       // uf.setVisible(true);
    }//GEN-LAST:event_bUbraniaActionPerformed

    private void bZwrotyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bZwrotyActionPerformed
        // TODO add your handling code here:
       // zf.setVisible(true);
    }//GEN-LAST:event_bZwrotyActionPerformed

    private void bLekarzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLekarzActionPerformed
        // TODO add your handling code here:
       // lf.setVisible(true);
    }//GEN-LAST:event_bLekarzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharakterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharakterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharakterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharakterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharakterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonIconD bCharakter;
    private rojerusan.RSButtonIconD bLekarz;
    private rojerusan.RSButtonPane bSprawdz;
    private rojerusan.RSButtonIconD bUbrania;
    private rojerusan.RSButtonPane bWylosuj;
    private rojerusan.RSButtonIconD bZwroty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea tSlowko;
    private javax.swing.JTextField tTlumacz;
    // End of variables declaration//GEN-END:variables
    private BazaDanych bd;
    private LekarzFrame lf;
    private UbraniaFrame uf;
    private ZwrotyFrame zf;
}
