/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formatki;

/**
 *
 * @author joann
 */
public class StartFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartFrame
     */
    public StartFrame() {
        initComponents();
        lf = new LekarzFrame();
        uf = new UbraniaFrame();
        zf = new ZwrotyFrame();
        cf = new CharakterFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lKategorie = new javax.swing.JLabel();
        bLekarz = new rojerusan.RSButtonPane();
        lLekarz = new javax.swing.JLabel();
        bCharakter = new rojerusan.RSButtonPane();
        lCharakter = new javax.swing.JLabel();
        bUbrania = new rojerusan.RSButtonPane();
        lUbrania = new javax.swing.JLabel();
        bZwroty = new rojerusan.RSButtonPane();
        lZwroty = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(46, 68, 133));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lKategorie.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lKategorie.setForeground(new java.awt.Color(213, 187, 155));
        lKategorie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formatki/ikonki/slownik.png"))); // NOI18N
        lKategorie.setLabelFor(jPanel1);
        lKategorie.setText("KATEGORIE");
        jPanel1.add(lKategorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 70));

        bLekarz.setBackground(new java.awt.Color(46, 68, 133));
        bLekarz.setColorHover(new java.awt.Color(33, 50, 103));
        bLekarz.setColorNormal(new java.awt.Color(46, 68, 133));
        bLekarz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLekarzMouseClicked(evt);
            }
        });

        lLekarz.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lLekarz.setForeground(new java.awt.Color(213, 187, 155));
        lLekarz.setLabelFor(bLekarz);
        lLekarz.setText("U lekarza");
        lLekarz.setMaximumSize(new java.awt.Dimension(116, 45));
        lLekarz.setMinimumSize(new java.awt.Dimension(116, 45));

        javax.swing.GroupLayout bLekarzLayout = new javax.swing.GroupLayout(bLekarz);
        bLekarz.setLayout(bLekarzLayout);
        bLekarzLayout.setHorizontalGroup(
            bLekarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bLekarzLayout.createSequentialGroup()
                .addComponent(lLekarz, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bLekarzLayout.setVerticalGroup(
            bLekarzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lLekarz, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(bLekarz, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 340, 60));

        bCharakter.setBackground(new java.awt.Color(46, 68, 133));
        bCharakter.setColorHover(new java.awt.Color(33, 50, 103));
        bCharakter.setColorNormal(new java.awt.Color(46, 68, 133));
        bCharakter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCharakterMouseClicked(evt);
            }
        });

        lCharakter.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lCharakter.setForeground(new java.awt.Color(213, 187, 155));
        lCharakter.setLabelFor(bUbrania);
        lCharakter.setText("Cechy charakteru");

        javax.swing.GroupLayout bCharakterLayout = new javax.swing.GroupLayout(bCharakter);
        bCharakter.setLayout(bCharakterLayout);
        bCharakterLayout.setHorizontalGroup(
            bCharakterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bCharakterLayout.createSequentialGroup()
                .addComponent(lCharakter)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bCharakterLayout.setVerticalGroup(
            bCharakterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bCharakterLayout.createSequentialGroup()
                .addComponent(lCharakter, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(bCharakter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 340, 60));

        bUbrania.setBackground(new java.awt.Color(46, 68, 133));
        bUbrania.setColorHover(new java.awt.Color(33, 50, 103));
        bUbrania.setColorNormal(new java.awt.Color(46, 68, 133));
        bUbrania.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bUbraniaMouseClicked(evt);
            }
        });

        lUbrania.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lUbrania.setForeground(new java.awt.Color(213, 187, 155));
        lUbrania.setLabelFor(bLekarz);
        lUbrania.setText("Ubrania");
        lUbrania.setMaximumSize(new java.awt.Dimension(116, 45));
        lUbrania.setMinimumSize(new java.awt.Dimension(116, 45));

        javax.swing.GroupLayout bUbraniaLayout = new javax.swing.GroupLayout(bUbrania);
        bUbrania.setLayout(bUbraniaLayout);
        bUbraniaLayout.setHorizontalGroup(
            bUbraniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bUbraniaLayout.createSequentialGroup()
                .addComponent(lUbrania, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bUbraniaLayout.setVerticalGroup(
            bUbraniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lUbrania, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(bUbrania, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 340, 60));

        bZwroty.setBackground(new java.awt.Color(46, 68, 133));
        bZwroty.setColorHover(new java.awt.Color(33, 50, 103));
        bZwroty.setColorNormal(new java.awt.Color(46, 68, 133));
        bZwroty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bZwrotyMouseClicked(evt);
            }
        });

        lZwroty.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lZwroty.setForeground(new java.awt.Color(213, 187, 155));
        lZwroty.setLabelFor(bLekarz);
        lZwroty.setText("Zwroty i wyrażenia");
        lZwroty.setMaximumSize(new java.awt.Dimension(116, 45));
        lZwroty.setMinimumSize(new java.awt.Dimension(116, 45));

        javax.swing.GroupLayout bZwrotyLayout = new javax.swing.GroupLayout(bZwroty);
        bZwroty.setLayout(bZwrotyLayout);
        bZwrotyLayout.setHorizontalGroup(
            bZwrotyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bZwrotyLayout.createSequentialGroup()
                .addComponent(lZwroty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 72, Short.MAX_VALUE))
        );
        bZwrotyLayout.setVerticalGroup(
            bZwrotyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lZwroty, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(bZwroty, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 340, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLekarzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLekarzMouseClicked
        // TODO add your handling code here:
        lf.setVisible(true);
        
    }//GEN-LAST:event_bLekarzMouseClicked

    private void bCharakterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCharakterMouseClicked
        // TODO add your handling code here:
        cf.setVisible(true);
    }//GEN-LAST:event_bCharakterMouseClicked

    private void bUbraniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bUbraniaMouseClicked
        // TODO add your handling code here:
        uf.setVisible(true);
    }//GEN-LAST:event_bUbraniaMouseClicked

    private void bZwrotyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bZwrotyMouseClicked
        // TODO add your handling code here:
        zf.setVisible(true);
    }//GEN-LAST:event_bZwrotyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonPane bCharakter;
    private rojerusan.RSButtonPane bLekarz;
    private rojerusan.RSButtonPane bUbrania;
    private rojerusan.RSButtonPane bZwroty;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lCharakter;
    private javax.swing.JLabel lKategorie;
    private javax.swing.JLabel lLekarz;
    private javax.swing.JLabel lUbrania;
    private javax.swing.JLabel lZwroty;
    // End of variables declaration//GEN-END:variables
    private final LekarzFrame lf;
    private final CharakterFrame cf;
    private final UbraniaFrame uf;
    private final ZwrotyFrame zf;
}
